name: cargo test mont1

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
#    defaults:
#      run:
#        working-directory: mont1

    steps:
      - uses: actions/checkout@v2
      - run: |
          cd mont1
          cargo test
#      - uses: actions-rs/cargo@v1
#        with:
#          command: test
